# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_tblbookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbookreview',
            name='chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblbookreview',
            name='tblbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.TblBook'),
            preserve_default=False,
        ),
    ]
